spring.application.name=helpnearby

server.port=8091

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/helpnearby
spring.datasource.username=root
spring.datasource.password=Abhishekjha@9693472315

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true